### PR TITLE
Additional updates for the roadmap

### PR DESCRIPTION
**Pull request by whimboo**
@mathiasbynens please merge as discussed. Thanks!

***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver-bidi/pull/362.html" title="Last updated on Feb 3, 2023, 5:03 PM UTC (ee94943)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/362/f227e83...whimboo:ee94943.html" title="Last updated on Feb 3, 2023, 5:03 PM UTC (ee94943)">Diff</a>

### CODE REVIEW

**Comment by whimboo** [comment]
There are conflicts with master so I'll have to rebase as well.

**Comment by whimboo** [comment]
@mathiasbynens your branch was very far behind. As such are that many commits listed. Now it should be ready and will also make the checks passing.

**Comment by mathiasbynens** [comment]
I think you meant to branch off of the `clarify-roadmap` branch, but instead branched off of `master`, resulting in many unrelated commits becoming part of this PR.

image

I’ll go ahead and manually copy over your changes to `roadmap.md` to the other branch.

**Comment by mathiasbynens** [comment]
Closing this since this is now integrated into #265. Thanks!

**Pull request closed without merging**
