### PR TITLE
WIP: Introduce Browser Permissions

### PR DESCRIPTION
**Pull request by thiagowfx**
Bug: #587
Spec: https://www.w3.org/TR/permissions/

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/590.html" title="Last updated on Nov 3, 2023, 3:10 PM UTC (7d738b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/590/a7adbf0...7d738b4.html" title="Last updated on Nov 3, 2023, 3:10 PM UTC (7d738b4)">Diff</a>

### CODE REVIEW

**Comment by thiagowfx** [comment]
Removed, maybe to re-add later, maybe not:

```
CDDL:
? origin: text,

Algorithm:
1. Let |origin| be the value of the <code>origin</code> field of |command
   parameters| if present, or null otherwise, representing an [=/origin=].

Meant to refer to https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setPermission
```

**Comment by thiagowfx** [comment]
cc @OrKoN

**Review by OrKoN — CHANGES_REQUESTED** [review]
Let's draft it as an extension in https://www.w3.org/TR/permissions/

**Comment by thiagowfx** [comment]
Sounds good. Closing this PR, will rewrite it in the permissions spec repo: https://github.com/w3c/permissions/

**Pull request closed without merging**
