### PR TITLE
Editorial: rename "respond with an error"

### PR DESCRIPTION
**Pull request by jugglinmike**
The proposal defines "error" as an internal type for describing one kind of result of fallible algorithms, and it defines "ErrorResponse" as a type of message which may be sent to clients. The algorithm used to transmit error responses to clients is named "respond with an error" even though it does not use the "error" type.

Rename "respond with an error" to "send an error response" to more accurately describe the types involved.

***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/webdriver-bidi/pull/331.html" title="Last updated on Nov 30, 2022, 2:42 AM UTC (89ce99b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/331/604cadb...bocoup:89ce99b.html" title="Last updated on Nov 30, 2022, 2:42 AM UTC (89ce99b)">Diff</a>

### CODE REVIEW

**Comment by jgraham** [comment]
I'm not convinced that this is a noticable improvement, but if other are I'm happy for them to review.

**Review by sadym-chromium — APPROVED** [review]
LGTM

**Comment by whimboo** [comment]
@jugglinmike the PR has merge conflicts. Would you mind fixing these so that we can merge? Thanks!

**Comment by jugglinmike** [comment]
@whimboo Sure. It's all set, now.

**Comment by whimboo** [comment]
Thanks!

**Pull request merged**
