### PR TITLE
Rename `warning` to `warn`

### PR DESCRIPTION
**Pull request by sadym-chromium**
Rename `warning` to `warn` to align with the `console` API.
Remove `console.warning` mention, as there is no such a method.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/259.html" title="Last updated on Oct 19, 2022, 7:33 PM UTC (9a77f87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/259/9062b1d...9a77f87.html" title="Last updated on Oct 19, 2022, 7:33 PM UTC (9a77f87)">Diff</a>

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Makes sense to me.

**Comment by whimboo** [comment]
@sadym-chromium would you mind creating a wpt PR to change that in the `test_level` test method in `console.py`?

**Comment by jgraham** [comment]
Seems reasonable to land subject to a test change PR.

**Comment by sadym-chromium** [comment]
> @sadym-chromium would you mind creating a wpt PR to change that in the `test_level` test method in `console.py`?

done

**Pull request merged**
