### PR TITLE
Line number of stack frame needs to be zero-based

### PR DESCRIPTION
**Pull request by whimboo**
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver-bidi/pull/154.html" title="Last updated on Dec 2, 2021, 9:03 AM UTC (538c8cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/154/f5ce465...whimboo:538c8cd.html" title="Last updated on Dec 2, 2021, 9:03 AM UTC (538c8cd)">Diff</a>

### CODE REVIEW

**Comment by foolip** [comment]
What's the precedent from existing debugging protocols on this?

**Comment by jgraham** [comment]
CDP is [zero based for everything](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-CallFrame). 

HTML error reporting [seems to be](https://software.hixie.ch/utilities/js/live-dom-viewer/saved/9864) seems to be different per browser: In Firefox I get one-based line numbers, and  zero based for column numbers assuming that it's using the position right before"new" as the column. In Chrome the line numbers seem to be zero based and the column numbers seem to be one-based assuming it's using the position right before "throw" as the column.

Puppeteer seems to use the CDP values directly.

**Comment by whimboo** [comment]
Sorry, for not having added the details why I'm proposing the change. I was side-tracked until now. So thanks a lot @jgraham for doing it.

**Comment by whimboo** [comment]
@foolip did the reply from @jgraham help to understand the current situation? Is there something else that we need to make progress on this particular change? Currently I'm implementing stack handling for `log.entryAdded` for Firefox, so adding the right set of WebDriver tests would be good. 

Please let us know if something is missing or unclear. Thanks a lot.

**Comment by foolip** [comment]
Alright, let's go with zero-based!

**Review by foolip — APPROVED** [review]

**Pull request merged**
