### PR TITLE
Fix remote value mapping for function, window and (platform) objects

### LINKED ISSUE #295: Broken remote value mapping for function, window and (platform) objects
For a couple of JavaScript types the serialization steps are broken because these do not reference remote types but local ones. Affected are the serialization of function, window, and (platform) object.

> Let remote value be a map matching the WindowProxyValue production in the [local end definition](https://w3c.github.io/webdriver-bidi/#local-end-definition),

Instead of `WindowProxyValue` it should be `WindowProxyRemoteValue`

### PR DESCRIPTION
**Pull request by whimboo**
Fix #295.

***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver-bidi/pull/296.html" title="Last updated on Sep 27, 2022, 6:18 PM UTC (9c9d2ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/296/8a1fc40...whimboo:9c9d2ef.html" title="Last updated on Sep 27, 2022, 6:18 PM UTC (9c9d2ef)">Diff</a>

### CODE REVIEW

**Review by sadym-chromium — APPROVED** [review]

**Review by juliandescottes — APPROVED** [review]
Thanks!

**Comment by whimboo** [comment]
Note that there are issues with the CDDL validation. I cannot see that my changes caused these failures so I'll have a look and may attach an additional commit to this PR.

**Comment by whimboo** [comment]
I was able to verify that my changes are fine and do not cause a failure locally. Instead it is caused by the [new 0.9.0 release of cddl](https://crates.io/crates/cddl/0.9.0).

I'll go ahead and merge my PR and will create a new issue / pull request to get cddl upgraded. As it looks like we now have way better checks!

**Comment by whimboo** [comment]
Btw I'll get issue #297 landed first.

**Pull request merged**
