### PR TITLE
Add document screenshots

### PR DESCRIPTION
**Pull request by jrandolf**
This PR implements document screenshots (formerly called "fullscreen screenshots).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/558.html" title="Last updated on Sep 29, 2023, 12:00 PM UTC (278d435)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/558/f5ec682...278d435.html" title="Last updated on Sep 29, 2023, 12:00 PM UTC (278d435)">Diff</a>

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

**Comment by jgraham** [comment]
What's the long term goal here? On it's own this seems like a bad change because it's breaking existing implementations for no obvious reason. But I assume it's part of some larger plan around fullscreen screenshots?

**Comment by jrandolf** [comment]
> What's the long term goal here? On it's own this seems like a bad change because it's breaking existing implementations for no obvious reason. But I assume it's part of some larger plan around fullscreen screenshots?

Indeed. We internally discussed some solutions w.r.t. fullscreen screenshots and found that this is a common change among all proposed solutions.

**Comment by OrKoN** [comment]
@jgraham we posted a comment about the full page screenshots here https://github.com/w3c/webdriver-bidi/issues/384#issuecomment-1733324443 where we wanted to get some input from selenium or if you have thoughts on the proposed design?

Unrelated to that, I think we could also update the literal type here to be consistent (e.g., via is the BoxClipRectangle type being discriminated by the type="viewport"?). If you think renaming would be too costly, let's delay until we settle on the API for full page screenshots.

**Comment by jrandolf** [comment]
Closed in favor of https://github.com/w3c/webdriver-bidi/pull/564

**Pull request closed without merging**
