### PR TITLE
Move contents of webdriver-bidi dir from webdriver repo

### PR DESCRIPTION
**Pull request by foolip**
Source: https://github.com/w3c/webdriver/tree/9232973aab3d75a58b25870066c1d5fb47fabc46/webdriver-bidi

### CODE REVIEW

**Comment by foolip** [comment]
@bwalderman can you review? @AutomatedTester can you arrange for @bwalderman to have write access to this repo so it's possible to request review the usual way?

**Comment by foolip** [comment]
https://github.com/w3c/webdriver/pull/1509 is the other half of the move (the simpler half).

**Comment by jgraham** [comment]
I"m happy to merge this, but it looks like the openrpc stuff is related to the http variant rather than bidi?

**Comment by foolip** [comment]
@jgraham I didn't give it more than a cursory glance, but I see some stuff about BootstrapScriptId in there. I'll file issues in both repos about the machine readable questions.

**Pull request merged**
